-- Sprint 1 business-structure migration
-- Adds client onboarding type, structured assignment planning fields,
-- care plan services, and assignment lifecycle audits.

alter table if exists public.users
  add column if not exists client_onboarding_type text;

update public.users
set client_onboarding_type = 'kin_requested'
where role = 'client'
  and coalesce(client_onboarding_type, '') = '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_client_onboarding_type_check'
  ) then
    alter table public.users
      add constraint users_client_onboarding_type_check
      check (
        client_onboarding_type is null
        or client_onboarding_type in ('self_service', 'kin_requested')
      );
  end if;
end $$;

alter table if exists public.assignments
  add column if not exists service_plan_type text;

alter table if exists public.assignments
  add column if not exists approval_state text;

alter table if exists public.assignments
  add column if not exists care_shift text;

alter table if exists public.assignments
  add column if not exists monthly_visit_plan int;

alter table if exists public.assignments
  add column if not exists planned_visit_duration_minutes int;

alter table if exists public.assignments
  add column if not exists service_for_client_id bigint references public.users(id) on delete set null;

alter table if exists public.assignments
  add column if not exists extension_end_date date;

update public.assignments
set service_plan_type = case when coalesce(term_type, 'short') = 'long' then 'long_term' else 'short_term' end
where service_plan_type is null;

update public.assignments
set approval_state = 'approved'
where approval_state is null;

update public.assignments
set planned_visit_duration_minutes = 60
where service_plan_type = 'short_term'
  and planned_visit_duration_minutes is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_service_plan_type_check'
  ) then
    alter table public.assignments
      add constraint assignments_service_plan_type_check
      check (
        service_plan_type is null
        or service_plan_type in ('short_term', 'long_term')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_approval_state_check'
  ) then
    alter table public.assignments
      add constraint assignments_approval_state_check
      check (
        approval_state is null
        or approval_state in ('pending_approval', 'approved', 'rejected', 'rescheduled')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_care_shift_check'
  ) then
    alter table public.assignments
      add constraint assignments_care_shift_check
      check (
        care_shift is null
        or care_shift in ('morning_10h', 'night_10h', 'full_day')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_monthly_visit_plan_check'
  ) then
    alter table public.assignments
      add constraint assignments_monthly_visit_plan_check
      check (
        monthly_visit_plan is null
        or monthly_visit_plan in (3, 6, 9)
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_planned_visit_duration_check'
  ) then
    alter table public.assignments
      add constraint assignments_planned_visit_duration_check
      check (
        planned_visit_duration_minutes is null
        or planned_visit_duration_minutes in (60, 90)
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'assignments_extension_end_date_check'
  ) then
    alter table public.assignments
      add constraint assignments_extension_end_date_check
      check (
        extension_end_date is null
        or extension_end_date >= start_date
      );
  end if;
end $$;

create table if not exists public.care_plan_services (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  service_code text not null,
  service_name text not null,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  unique (assignment_id, service_code)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'care_plan_services_code_check'
  ) then
    alter table public.care_plan_services
      add constraint care_plan_services_code_check
      check (
        service_code in (
          'walking_companion',
          'conversation_emotional_support',
          'hospital_accompaniment',
          'medicine_pickup',
          'grocery_shopping_assistance',
          'technology_help',
          'monthly_family_updates'
        )
      );
  end if;
end $$;

create table if not exists public.assignment_lifecycle_audits (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_user_id bigint references public.users(id) on delete set null,
  notes text default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_care_plan_services_assignment
  on public.care_plan_services (assignment_id);

create index if not exists idx_assignment_lifecycle_audits_assignment_time
  on public.assignment_lifecycle_audits (assignment_id, created_at desc);
