-- Gatt and Co care operations schema
-- Supports three roles:
-- 1) admin   -> full control
-- 2) buddy   -> assigned case/task updates + location + status updates
-- 3) client  -> read-only transparency for parent visits and outcomes

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  full_name text not null,
  email text unique not null,
  phone text default '',
  address text default '',
  password_hash text not null,
  role text not null check (role in ('admin','buddy','client')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.elderly_members (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete cascade,
  full_name text not null,
  gender text,
  dob date,
  age int,
  blood_group text,
  medical_notes text default '',
  allergies text default '',
  address text default '',
  emergency_contact_name text,
  emergency_contact_phone text,
  care_start_date date default current_date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (age is null or age between 0 and 130)
);

-- Optional: multiple daughters/sons can see the same elderly profile.
create table if not exists public.elderly_client_access (
  id bigint generated by default as identity primary key,
  elderly_id bigint not null references public.elderly_members(id) on delete cascade,
  client_user_id bigint not null references public.users(id) on delete cascade,
  relation_label text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (elderly_id, client_user_id)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  buddy_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint not null references public.elderly_members(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'paused', 'completed', 'cancelled')),
  term_type text default 'short' check (term_type in ('short', 'long')),
  start_date date not null default current_date,
  end_date date,
  admin_notes text,
  created_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);

-- Optional enforcement: only one active assignment per buddy/elderly pair.
create unique index if not exists uq_assignments_active_pair
  on public.assignments (buddy_id, elderly_id)
  where status = 'active';

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  buddy_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint not null references public.elderly_members(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete set null,
  scheduled_date date not null,
  visit_status text not null default 'scheduled' check (visit_status in ('scheduled', 'in_progress', 'completed', 'missed', 'cancelled')),
  arrival_time timestamptz,
  departure_time timestamptz,
  arrival_lat_lng text,
  status_check text,
  buddy_notes text,
  client_visible_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (departure_time is null or arrival_time is null or departure_time >= arrival_time)
);

create table if not exists public.visit_tasks (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.visits(id) on delete cascade,
  task_name text not null,
  task_category text,
  status text not null default 'pending' check (status in ('pending', 'completed', 'done', 'carried_forward', 'skipped')),
  measured_value text,
  measured_unit text,
  buddy_remarks text,
  client_visible_remarks text,
  due_at timestamptz,
  completed_at timestamptz,
  carried_forward_from_task_id bigint references public.visit_tasks(id) on delete set null,
  carry_forward_reason text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Structured location history for transparency and audit.
create table if not exists public.buddy_location_logs (
  id bigint generated by default as identity primary key,
  buddy_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint references public.elderly_members(id) on delete set null,
  visit_id bigint references public.visits(id) on delete set null,
  latitude numeric(9, 6) not null,
  longitude numeric(9, 6) not null,
  accuracy_m numeric(8, 2),
  source text default 'gps',
  recorded_at timestamptz not null default now()
);

-- Daily status checks (vitals/wellness/safety etc.).
create table if not exists public.visit_status_checks (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.visits(id) on delete cascade,
  check_type text not null check (check_type in ('general', 'vitals', 'mood', 'medication', 'mobility', 'hydration', 'nutrition', 'safety', 'other')),
  severity text not null default 'good' check (severity in ('good', 'attention', 'critical', 'na')),
  metric_name text,
  metric_value text,
  notes text,
  recorded_by bigint references public.users(id) on delete set null,
  recorded_at timestamptz not null default now()
);

create table if not exists public.client_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint references public.elderly_members(id) on delete set null,
  request_type text not null default 'general',
  message text not null,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists idx_users_role on public.users(role);
create index if not exists idx_elderly_client_id on public.elderly_members(client_id);
create index if not exists idx_assignments_buddy on public.assignments(buddy_id);
create index if not exists idx_assignments_elderly on public.assignments(elderly_id);
create index if not exists idx_visits_buddy_date on public.visits(buddy_id, scheduled_date desc);
create index if not exists idx_visits_elderly_date on public.visits(elderly_id, scheduled_date desc);
create index if not exists idx_visit_tasks_visit on public.visit_tasks(visit_id);
create index if not exists idx_location_logs_visit_time on public.buddy_location_logs(visit_id, recorded_at desc);
create index if not exists idx_status_checks_visit_time on public.visit_status_checks(visit_id, recorded_at desc);
create index if not exists idx_client_requests_user_time on public.client_requests(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_elderly_members_updated_at on public.elderly_members;
create trigger trg_elderly_members_updated_at
before update on public.elderly_members
for each row execute function public.set_updated_at();

drop trigger if exists trg_assignments_updated_at on public.assignments;
create trigger trg_assignments_updated_at
before update on public.assignments
for each row execute function public.set_updated_at();

drop trigger if exists trg_visits_updated_at on public.visits;
create trigger trg_visits_updated_at
before update on public.visits
for each row execute function public.set_updated_at();
