-- Adds storage for short-term assignment visit date + start-time planning.

begin;

create table if not exists public.short_term_visit_slots (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  buddy_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint not null references public.elderly_members(id) on delete cascade,
  visit_date date not null,
  start_time time not null,
  end_time time not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (end_at > start_at),
  unique (assignment_id, visit_date)
);

create index if not exists idx_short_term_slots_buddy_start
  on public.short_term_visit_slots (buddy_id, start_at asc);

commit;
