-- Adds multi-family contact support for each client profile.
-- Run this in Supabase SQL Editor for existing deployments.

alter table if exists public.assignments add column if not exists archived_at timestamptz;
alter table if exists public.visits add column if not exists archived_at timestamptz;
alter table if exists public.visit_tasks add column if not exists archived_at timestamptz;
alter table if exists public.client_requests add column if not exists archived_at timestamptz;

create table if not exists public.client_family_contacts (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint not null references public.elderly_members(id) on delete cascade,
  contact_name text default '',
  relation_label text default '',
  phone text not null,
  whatsapp_opt_in boolean not null default true,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, phone)
);

with ranked_contacts as (
  select
    id,
    row_number() over (
      partition by client_id
      order by is_primary desc, created_at asc, id asc
    ) as contact_rank
  from public.client_family_contacts
)
update public.client_family_contacts as target
set is_primary = ranked_contacts.contact_rank = 1
from ranked_contacts
where target.id = ranked_contacts.id;

create unique index if not exists uq_client_family_contacts_primary
  on public.client_family_contacts (client_id)
  where is_primary = true;

create table if not exists public.client_family_contact_audits (
  id bigint generated by default as identity primary key,
  family_contact_id bigint references public.client_family_contacts(id) on delete set null,
  client_id bigint not null references public.users(id) on delete cascade,
  elderly_id bigint references public.elderly_members(id) on delete set null,
  actor_user_id bigint references public.users(id) on delete set null,
  action_type text not null check (action_type in ('created', 'updated', 'deleted', 'primary_changed')),
  contact_name text default '',
  relation_label text default '',
  phone text default '',
  whatsapp_opt_in boolean not null default false,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

alter table if exists public.client_family_contact_audits add column if not exists archived_at timestamptz;

create table if not exists public.notification_action_logs (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete cascade,
  family_contact_id bigint references public.client_family_contacts(id) on delete set null,
  actor_user_id bigint references public.users(id) on delete set null,
  recipient_role text not null check (recipient_role in ('client', 'family')),
  recipient_name text default '',
  recipient_phone text default '',
  channel text not null check (channel in ('notify', 'whatsapp', 'sms', 'call')),
  template_key text not null,
  message_preview text default '',
  created_at timestamptz not null default now()
);

alter table if exists public.notification_action_logs add column if not exists archived_at timestamptz;

create table if not exists public.archive_purge_logs (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete cascade,
  actor_user_id bigint references public.users(id) on delete set null,
  archive_month text not null,
  assignments_deleted int not null default 0,
  visits_deleted int not null default 0,
  tasks_deleted int not null default 0,
  requests_deleted int not null default 0,
  contact_audits_deleted int not null default 0,
  notifications_deleted int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_client_family_contacts_client on public.client_family_contacts(client_id);
create index if not exists idx_client_family_contacts_elderly on public.client_family_contacts(elderly_id);
create index if not exists idx_client_family_contact_audits_client_time on public.client_family_contact_audits(client_id, created_at desc);
create index if not exists idx_client_family_contact_audits_contact_time on public.client_family_contact_audits(family_contact_id, created_at desc);
create index if not exists idx_notification_action_logs_client_time on public.notification_action_logs(client_id, created_at desc);
create index if not exists idx_notification_action_logs_contact_time on public.notification_action_logs(family_contact_id, created_at desc);
create index if not exists idx_archive_purge_logs_client_time on public.archive_purge_logs(client_id, created_at desc);

drop trigger if exists trg_client_family_contacts_updated_at on public.client_family_contacts;

create trigger trg_client_family_contacts_updated_at
before update on public.client_family_contacts
for each row execute function public.set_updated_at();
