-- Sprint 4 long-term daily records migration
-- Adds visit_sessions table for assignment-based daily presence records.

create table if not exists public.visit_sessions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  visit_id bigint references public.visits(id) on delete set null,
  session_date date not null,
  intime timestamptz,
  outtime timestamptz,
  entry_notes text default '',
  exit_notes text default '',
  backfilled boolean not null default false,
  backfill_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, session_date),
  check (outtime is null or intime is null or outtime >= intime)
);

create index if not exists idx_visit_sessions_assignment_date
  on public.visit_sessions(assignment_id, session_date desc);

create index if not exists idx_visit_sessions_visit
  on public.visit_sessions(visit_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_visit_sessions_updated_at on public.visit_sessions;
create trigger trg_visit_sessions_updated_at
before update on public.visit_sessions
for each row execute function public.set_updated_at();
